spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.batch.jdbc.initialize-schema=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
server.port=${SERVER_PORT}
server.error.include-message=always
productService.getProductDetails.url=http://${PRODUCT_SERVICE_URL:product-service}:${PRODUCT_SERVICE_PORT}/products/{productId}
userService.getUserById.url=http://${USER_SERVICE_URL:user-service}:${USER_SERVICE_PORT}/users/{userId}
security.jwt.secret=${JWT_SECRET:5bd214d237a17f400c02398b12c5d5293c0965a40412ded8c814f15cd099994398c7f3b4bfaf0c517c87c33adbd3d6b97317fce6441e8be7541bf72a65d57a3d}
management.endpoints.web.exposure.include=health