server:
  port: ${SERVER_PORT}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://${USER_SERVICE_URL}:${USER_SERVICE_PORT}
              predicates:
                - Path=/users/**, /alerts/**
            - id: product-service
              uri: http://${PRODUCT_SERVICE_URL}:${PRODUCT_SERVICE_PORT}
              predicates:
                - Path=/products/**, /categories/**, /items/**, /bookings/**
            - id: notification-service
              uri: http://${NOTIFICATION_SERVICE_URL}:${NOTIFICATION_SERVICE_PORT}
              predicates:
                - Path=/notifications/**
            - id: digital-service
              uri: http://${DIGITAL_SERVICE_URL}:${DIGITAL_SERVICE_PORT}
              predicates:
                - Path=/digital/**, /digitalItem/**
            - id: auth-service
              uri: http://${AUTH_SERVICE_URL}:${AUTH_SERVICE_PORT}
              predicates:
                - Path=/auth/**
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG