server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://localhost:18082
              predicates:
                - Path=/users/**, /alerts/**
            - id: product-service
              uri: http://localhost:18081
              predicates:
                - Path=/products/**, /categories/**, /items/**, /bookings/**
            - id: notification-service
              uri: http://localhost:18083
              predicates:
                - Path=/notifications/**
            - id: digital-service
              uri: http://localhost:18084
              predicates:
                - Path=/digital/**, /digitalItem/**
            - id: auth-service
              uri: http://localhost:18085
              predicates:
                - Path=/auth/**