sonar.projectName=Frontend

sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**
sonar.tests=src,e2e
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info,coverage-e2e/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage-e2e/lcov.info
