spring.datasource.url=jdbc:postgresql://localhost:54320/product
spring.datasource.username=product
spring.datasource.password=product
spring.kafka.bootstrap-servers=localhost:19092
server.port=18081
userService.getUserByEmail.url=http://localhost:18082/users/byEmail/{email}
security.jwt.secret=5bd214d237a17f400c02398b12c5d5293c0965a40412ded8c814f15cd099994398c7f3b4bfaf0c517c87c33adbd3d6b97317fce6441e8be7541bf72a65d57a3d
