<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.2</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>edu.uoc.epcsd</groupId>
    <artifactId>productcatalog</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>productcatalog</name>
    <description>ProductCatalog Spring Boot stub for EPCSD</description>
  <build>
    <plugins>

      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <artifactId>mapstruct-processor</artifactId>
              <groupId>org.mapstruct</groupId>
              <version>${mapstruct.version}</version>
            </path>
            <path>
              <artifactId>lombok</artifactId>
              <groupId>org.projectlombok</groupId>
              <version>${lombok.version}</version>
            </path>
            <path>
              <artifactId>lombok-mapstruct-binding</artifactId>
              <groupId>org.projectlombok</groupId>
              <version>${lombok-mapstruct-binding.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
      </plugin>

      <plugin>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>
              <artifactId>lombok</artifactId>
              <groupId>org.projectlombok</groupId>
            </exclude>
          </excludes>
        </configuration>
        <groupId>org.springframework.boot</groupId>
      </plugin>

      <plugin>
        <artifactId>sonar-maven-plugin</artifactId>
        <groupId>org.sonarsource.scanner.maven</groupId>
        <version>5.2.0.4988</version>
      </plugin>

      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <argLine>${argLine}</argLine>
          <excludes>
            <exclude>**/*IT.class</exclude>
          </excludes>
          <trimStackTrace>false</trimStackTrace>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.5.4</version>
      </plugin>

      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <configuration>
          <argLine>${argLine}</argLine>
          <includes>
            <include>**/*IT.java</include>
          </includes>
          <trimStackTrace>false</trimStackTrace>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
            </goals>
            <id>integration-test</id>
          </execution>
          <execution>
            <goals>
              <goal>verify</goal>
            </goals>
            <id>verify</id>
          </execution>
        </executions>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.5.4</version>
      </plugin>

      <plugin>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report</id>
            <phase>verify</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
        <artifactId>jacoco-maven-plugin</artifactId>
        <groupId>org.jacoco</groupId>
        <version>0.8.14</version>
      </plugin>
    </plugins>
  </build>

  <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
    <dependency>
      <artifactId>spring-boot-starter-actuator</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jersey</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.5</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
          <artifactId>lombok</artifactId>
          <groupId>org.projectlombok</groupId>
          <optional>true</optional>
          <version>${lombok.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>kafka</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>postgresql</artifactId>
            <scope>test</scope>
        </dependency>
      <dependency>
        <artifactId>jjwt-api</artifactId>
        <groupId>io.jsonwebtoken</groupId>
        <version>${jjwt.version}</version>
      </dependency>
      <dependency>
        <artifactId>jjwt-impl</artifactId>
        <groupId>io.jsonwebtoken</groupId>
        <scope>runtime</scope>
        <version>${jjwt.version}</version>
      </dependency>
      <dependency>
        <artifactId>jjwt-jackson</artifactId>
        <groupId>io.jsonwebtoken</groupId>
        <scope>runtime</scope>
        <version>${jjwt.version}</version>
      </dependency>
      <dependency>
        <artifactId>spring-boot-starter-security</artifactId>
        <groupId>org.springframework.boot</groupId>
      </dependency>
    <dependency>
      <artifactId>spring-security-test</artifactId>
      <groupId>org.springframework.security</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
        <artifactId>commons-collections4</artifactId>
        <groupId>org.apache.commons</groupId>
        <version>${apache-commons.version}</version>
      </dependency>
      <dependency>
        <artifactId>mapstruct</artifactId>
        <groupId>org.mapstruct</groupId>
        <version>${mapstruct.version}</version>
      </dependency>
    </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <artifactId>testcontainers-bom</artifactId>
        <groupId>org.testcontainers</groupId>
        <scope>import</scope>
        <type>pom</type>
        <version>${testcontainers.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

    <properties>
      <java.version>11</java.version>
      <testcontainers.version>1.21.3</testcontainers.version>
      <jjwt.version>0.13.0</jjwt.version>
      <apache-commons.version>4.5.0</apache-commons.version>
      <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
      <lombok.version>1.18.42</lombok.version>
      <mapstruct.version>1.6.3</mapstruct.version>
    </properties>

</project>
