spring.datasource.url=jdbc:postgresql://localhost:54322/notification
spring.datasource.username=notification
spring.datasource.password=notification
server.port=18083
spring.kafka.bootstrap-servers=localhost:19092
userService.getUsersToAlert.url=http://localhost:18082/internal/users/toAlert?productId={productId}&availableOnDate={availableOnDate}
productService.getProductDetails.url=http://localhost:18081/products/{productId}
digitalItemService.getDigitalItemToAlert.url=http://localhost:18084/internal/digitalItem/{digitalItemId}/alert
security.jwt.secret=5bd214d237a17f400c02398b12c5d5293c0965a40412ded8c814f15cd099994398c7f3b4bfaf0c517c87c33adbd3d6b97317fce6441e8be7541bf72a65d57a3d